name = "Mayview"
author = "jflec"
version = "Beta 0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa1ed1c293636ec49cf64c16d0e25eedb862242e501fb5d2160224d5703be181"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
