name = "Mayview"
author = "jflec"
version = "Beta 0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f081f8bba4cb129f013c9f047e5eaee38e2cfd4caba49a15bdd4f028db69bfa2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
datapack-folder = "./resourcepacks"
